source "https://rubygems.org"

# Declare your default dependencies that you're using in your jobs
gem "colorize", ">= 0.7"
gem "sqlite3", ">= 1.3.11"

# Development dependencies are not loaded by default. Declare them
# here and require if needed. The ony exception is "Pry". Pry will
# be required automatically if available.
# The metacrunch dependency is needed for some demo jobs that need
# access to metacrunch/test_utils.
group :development do
  gem "metacrunch", ">= 3.0.0"
  gem "pry-byebug", ">= 3.3.0"
  gem "pry-rescue", ">= 1.4.2"
  gem "pry-state",  ">= 0.1.7"
end
